### ISSUE TITLE
error reading the mask images

### ISSUE THREAD

**Issue by heba9004** [koriavinash1/DigitalHistoPath#17]
First of all thank you for sharing such an excellent project. I am planning to run your scripts on the PAIP dataset 2019, I uncompressed the training files then I started from your "points_extractor.py" file to prepare the patches but I faced some difficulty in reading the binary masks (tif files), their path returns "none" while the path exists and it give the following error (OpenSlideUnsupportedFormatError) . Any suggestion how to solve this? 

Also your help in stating the order of the files that must be executed to reach the training phase is really appreciated.

**Comment by haranrk** [comment]
Hi, I'm happy to know that you find our project useful. 
The mask images of PAIP2019 are not in open slide format. Therefore, you would need to convert them to an open slide format, before OpenSlide can read it. 
The following command uses imagemagick to convert an image to pyramidal format:
```bash
convert input.tiff -compress jpeg -quality 90 -define tiff:tile-geometry=256x256 ptif:output.tiff
```
Although the file extensions for both the images are the same, the normal image is a normal `tif` file where as the output image is a pyramidal `tif` file.

[Source](https://github.com/openslide/openslide/wiki/CreatingPyramidalTIFFs)

**Comment by heba9004** [comment]
Thank you very much for the quick response. I started converting them, but the conversion process is really slow, I think this is related to the large size of the images.
